name: release

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ["distribution-spec/**"]

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare
        id: prep
        run: |
          cd ./distribution-spec/conformance
          VERSION=$(git rev-parse --short HEAD)
          git apply ../../mirror.patch
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
      - name: Generate images meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/spegel-org/conformance
          tags: type=raw,value=${{ steps.prep.outputs.VERSION }}
      - name: Publish multi-arch image
        uses: docker/build-push-action@v5
        id: build
        with:
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./distribution-spec/conformance/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/spegel-org/conformance:${{ steps.prep.outputs.VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
