name: release

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ["distribution-spec/**"]

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:        
          submodules: true
      - name: Setup QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 #v3.6.0
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 #v3.10.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 #v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare
        id: prep
        run: |
          cd ./distribution-spec/conformance
          VERSION=$(git rev-parse --short HEAD)
          git apply ../../mirror.patch
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
      - name: Generate images meta
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 #v5.7.0
        with:
          images: ghcr.io/spegel-org/conformance
          tags: type=raw,value=${{ steps.prep.outputs.VERSION }}
      - name: Publish multi-arch image
        uses: docker/build-push-action@1dc73863535b631f98b2378be8619f83b136f4a0 #v6.17.0
        id: build
        with:
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          context: ./distribution-spec/conformance
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/spegel-org/conformance:${{ steps.prep.outputs.VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
